name: e2e-test 🪨 

on:
  push:
    branches:
    - main
    - 'releases/**'
    tags:
      - '*'
  pull_request:
    branches:
    - main
    - 'releases/**'
  
  workflow_dispatch:
  
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_REPO }}/passthrough-connector

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Checkout Docker container
      run: docker pull ${{ env.IMAGE_NAME }}:latest

    - name: Run Docker container
      run: docker run -d -p 8010:80 -e AUTH_TYPE=${{ secrets.AUTH_TYPE }} -e API_KEY=${{ secrets.API_KEY }} -e SERVER_URL=${{ secrets.SERVER_URL }} ${{ env.IMAGE_NAME }}:latest
